import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { TextField } from "src/components";
import { Formik, Form } from "formik";
import * as Yup from "yup";

function auth() {
  const [auth, setAuth] = useState<"signup" | "signin">("signin");

  const toggleAuth = (state: "signup" | "signin") => {
    setAuth(state);
  };

  const onSubmit = (formData: { email: string; password: string }) => {
    console.log(formData);
  };

  const validation = Yup.object({
    email: Yup.string()
      .email("Enter valid email")
      .required("Email is required"),
    password: Yup.string()
      .min(4, "4 minimum character")
      .required("Password is required"),
  });

  return (
    <div className="relative flex h-screen w-screen md:justify-center md:items-center bg-black md:bg-transparent">
      <Head>
        <title>Auth page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image
        src={
          "https://assets.nflxext.com/ffe/siteui/vlv3/d0982892-13ac-4702-b9fa-87a410c1f2da/519e3d3a-1c8c-4fdb-8f8a-7eabdbe87056/AE-en-20220321-popsignuptwoweeks-perspective_alpha_website_large.jpg"
        }
        alt="bg img"
        fill
        className="object-cover -z-10 !hidden sm:!inline opacity-50"
      />

      <Image
        className={" absolute let-4 top-4 cursor-pointer object-contain"}
        src={"/logo.svg"}
        alt={"logo"}
        width={70}
        height={70}
      />

      <div className="relative mt-24 space-y-8 bg-black/75 py-10 px-6 md:mt-0 md:max-w-md md:px-14">
        <h1 className="text-4xl font-semibold">
          {auth === "signup" ? "Sign Up" : "Sign In"}
        </h1>
        <Formik
          initialValues={{ email: "", password: "" }}
          onSubmit={onSubmit}
          validationSchema={validation}
        >
          <Form>
            <div className="space-y-4">
              <TextField name="email" type={"text"} placeholder="Email" />
              <TextField
                name="password"
                type={"password"}
                placeholder="Password"
              />
            </div>

            {auth === "signin" ? (
              <button className="w-full bg-red-500 py-3 font-semibold mt-4">
                Sig In
              </button>
            ) : (
              <button className="w-full bg-red-500 py-3 font-semibold">
                Sig Up
              </button>
            )}
          </Form>
        </Formik>

        {auth === "signup" ? (
          <div className="text-[gray] ">
            Already have account?{" "}
            <button
              onClick={() => toggleAuth("signin")}
              type="button"
              className="text-white hover:underline"
            >
              Sign In
            </button>
          </div>
        ) : (
          <div className="text-[gray]">
            Not yet account?{" "}
            <button
              onClick={() => toggleAuth("signup")}
              type="button"
              className="text-white hover:underline"
            >
              Sign Up Now
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

export default auth;
