import Head from "next/head";
import { Header } from "src/components";
import { GetServerSideProps } from "next";
import { API_REQUEST } from "../services/api.services";
import { IMovie } from "../interface/app.interface";

export default function Home({ trending }: HomeProps): JSX.Element {
  console.log(trending);

  return (
    <div className="relative h-[250vh] ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <main></main>
    </div>
  );
}
export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  const trending = await fetch(API_REQUEST.trending).then((res) => res.json());

  return {
    props: {
      trending: trending.results,
    },
  };
};

interface HomeProps {
  trending: IMovie[];
}
